export const LOGIN_REQUEST = '[LOGIN_REQUEST]';
export const LOGIN_SUCCESS = '[LOGIN_SUCCESS]';
export const LOGIN_FAILED = '[LOGIN_FAILED]';

export const GET_USERS_REQUEST = '[GET_USERS_REQUEST]';
export const GET_USERS_SUCCESS = '[GET_USERS_SUCCESS]';
export const GET_USERS_FAILED = '[GET_USERS_FAILED]';

export const GET_USER_REQUEST = '[GET_USER_REQUEST]';
export const GET_USER_SUCCESS = '[GET_USER_SUCCESS]';
export const GET_USER_FAILED = '[GET_USER_FAILED]';

export const GET_CALL_LOG_REQUEST = '[GET_CALL_LOG_REQUEST]';
export const GET_CALL_LOG_SUCCESS = '[GET_CALL_LOG_SUCCESS]';
export const GET_CALL_LOG_FAILED = '[GET_CALL_LOG_FAILED]';

export const GET_USER_APPROVALS_REQUEST = '[GET_USER_APPROVALS_REQUEST]';
export const GET_USER_APPROVALS_SUCCESS = '[GET_USER_APPROVALS_SUCCESS]';
export const GET_USER_APPROVALS_FAILED = '[GET_GET_USER_APPROVALS_FAILED]';
