export const GET_USERS_REQUEST = '[GET_USERS_REQUEST]';
export const GET_USERS_SUCCESS = '[GET_USERS_SUCCESS]';
export const GET_USERS_FAILED = '[GET_USERS_FAILED]';

export const GET_USER_REQUEST = '[GET_USER_REQUEST]';
export const GET_USER_SUCCESS = '[GET_USER_SUCCESS]';
export const GET_USER_FAILED = '[GET_USER_FAILED]';
